### ISSUE TITLE
How to pass unicode string to dart in delphi?

### ISSUE THREAD

**Issue by jonahzheng** [ilopX/connecting_dart_lang_with_others#1]
ex:

function CallNative(const a: Integer; str: PChar): PChar; stdcall;
var
  DartReturn: string;
  FomratStr: string;
begin

  FomratStr  := 'Pascal( ' + #13#10
    + '   CallNative(' + IntToStr(a) + ', ' + String(str) + ')' + #13#10
    + '   dartFunction() return ' + DartReturn  + #13#10
    + ')';

  Result  := FomratStr;
end;

**Comment by ilopX** [comment]
Hi, @jonahzheng! Thanks for your request.
In the dart code, we need to use Pointer <utf16> and the toNativeUtf16() converter.

https://github.com/ilopX/connecting_dart_lang_with_others/blob/677ea3de53024e30a9c3b638d9ef8b7c5fc0e3d9/bin/_06_delphi_callback.dart#L20-L25

https://github.com/ilopX/connecting_dart_lang_with_others/blob/677ea3de53024e30a9c3b638d9ef8b7c5fc0e3d9/native_libs/delphi_callback/delphi_callback.dpr#L19-L32
